# Generated by Django 5.2.3 on 2025-06-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='artikel_images/'),
        ),
    ]
